r"""
Installer builder -- creates platform installers from a Nuitka dist build.

  Windows:  Inno Setup  (.exe installer)
  Linux:    AppImage    (.AppImage portable bundle)

Prerequisites
-------------
Windows:
  - Inno Setup 6+  installed  (https://jrsoftware.org/isinfo.php)
  - ISCC.exe on PATH  -- or set  INNO_DIR  env-var to the install folder
    e.g.  set INNO_DIR=C:\Program Files (x86)\Inno Setup 6

Linux:
  - appimagetool  on PATH  (https://appimage.github.io/appimagetool/)
  - or set  APPIMAGETOOL  env-var to the full binary path

Usage
-----
  python installer.py                    # build for current platform
  python installer.py --platform windows # explicit
  python installer.py --platform linux
  python installer.py --platform all     # both (cross-build)
"""

import argparse
import os
import platform
import shutil
import subprocess
import stat
import sys
import textwrap

from app_config import APP_NAME, APP_VERSION, ICON_PATH

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
DIST_DIR     = os.path.join(SCRIPT_DIR, "dist", "main.dist")
OUTPUT_DIR   = os.path.join(SCRIPT_DIR, "installers")
ICON_FILE    = os.path.join(SCRIPT_DIR, ICON_PATH)

# Sanitised names
SAFE_NAME    = APP_NAME.replace(" ", "-")   # Desktop-Monitor
EXE_NAME     = "main.exe"                   # Nuitka default for main.py


# ═══════════════════════════════════════════════════════════════════════════
# Windows — Inno Setup
# ═══════════════════════════════════════════════════════════════════════════

_INNO_SCRIPT = r"""
; --- Auto-generated by installer.py — do not edit manually ---
#define MyAppName      "__APP_NAME__"
#define MyAppVersion   "__APP_VERSION__"
#define MyAppExeName   "__EXE_NAME__"
#define MyDistDir      "__DIST_DIR__"
#define MyIconFile     "__ICON_FILE__"
#define MyOutputDir    "__OUTPUT_DIR__"
#define MyOutputBase   "__OUTPUT_BASE__"

[Setup]
AppId={{__APP_GUID__}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher=SassBoy
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputDir={#MyOutputDir}
OutputBaseFilename={#MyOutputBase}
Compression=lzma2/ultra64
SolidCompression=yes
SetupIconFile={#MyIconFile}
UninstallDisplayIcon={app}\{#MyAppExeName}
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64compatible
WizardStyle=modern
; Require Windows 10 or later
MinVersion=10.0
; Auto-close the app if it is running during install/upgrade
CloseApplications=force
CloseApplicationsFilter=*.exe

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional shortcuts:"
Name: "startmenu"; Description: "Create a &Start Menu shortcut"; GroupDescription: "Additional shortcuts:"; Flags: checkedonce

[Files]
; Copy entire Nuitka dist tree into the install folder
Source: "{#MyDistDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}";         Filename: "{app}\{#MyAppExeName}"; Tasks: startmenu
Name: "{autodesktop}\{#MyAppName}";    Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"; Tasks: startmenu

[Dirs]
; Ensure runtime dirs exist with write access so the app can create
; face-db subfolders & download updates without elevation
Name: "{app}\faces_db\good";  Permissions: users-modify
Name: "{app}\faces_db\bad";   Permissions: users-modify
Name: "{app}\metadata";       Permissions: users-modify
Name: "{app}\targets";        Permissions: users-modify
Name: "{app}\cache";          Permissions: users-modify
Name: "{app}\splash_assets";  Permissions: users-modify
Name: "{app}\models";         Permissions: users-modify

[UninstallDelete]
; Remove the entire install directory — including runtime-created files
; (cache, metadata, faces_db, settings.json, crash.log etc.) that were
; not part of the original [Files] install and would otherwise be left behind.
Type: filesandordirs; Name: "{app}"
; Remove the Start Menu group folder even if shortcuts remain inside it
Type: filesandordirs; Name: "{group}"

[Run]
; shellexec forces Inno to use ShellExecuteEx instead of CreateProcess.
; CreateProcess cannot honour a requireAdministrator manifest and returns
; error 740 (ERROR_ELEVATION_REQUIRED).  ShellExecuteEx triggers the UAC
; prompt correctly before handing off to the exe.
Filename: "{app}\{#MyAppExeName}"; Description: "Launch {#MyAppName}"; Flags: nowait postinstall skipifsilent shellexec
"""


def _find_iscc() -> str:
    """Locate the Inno Setup command-line compiler."""
    # 1. Environment override
    env_dir = os.environ.get("INNO_DIR", "")
    if env_dir:
        candidate = os.path.join(env_dir, "ISCC.exe")
        if os.path.isfile(candidate):
            return candidate

    # 2. On PATH
    found = shutil.which("ISCC") or shutil.which("ISCC.exe")
    if found:
        return found

    # 3. Common install locations
    for pf in [
        os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)"),
        os.environ.get("ProgramFiles", r"C:\Program Files"),
    ]:
        for ver in ("Inno Setup 6", "Inno Setup 5"):
            candidate = os.path.join(pf, ver, "ISCC.exe")
            if os.path.isfile(candidate):
                return candidate

    return ""


def build_windows_installer():
    """Generate an Inno Setup .iss script and compile it into an installer."""
    print("\n[installer] Building Windows installer (Inno Setup) …")

    if not os.path.isdir(DIST_DIR):
        sys.exit(f"[ERROR] Nuitka dist not found at: {DIST_DIR}\n"
                 "        Run build.py first.")

    iscc = _find_iscc()
    if not iscc:
        sys.exit(
            "[ERROR] Inno Setup compiler (ISCC.exe) not found.\n"
            "        Install Inno Setup 6: https://jrsoftware.org/isinfo.php\n"
            "        Or set INNO_DIR=<install folder>"
        )

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Deterministic GUID derived from app name (consistent across rebuilds)
    import uuid
    app_guid = str(uuid.uuid5(uuid.NAMESPACE_DNS, APP_NAME))

    output_base = f"{SAFE_NAME}-{APP_VERSION}-Setup"

    iss_content = (_INNO_SCRIPT
        .replace("__APP_NAME__", APP_NAME)
        .replace("__APP_VERSION__", APP_VERSION)
        .replace("__EXE_NAME__", EXE_NAME)
        .replace("__DIST_DIR__", str(DIST_DIR))
        .replace("__ICON_FILE__", str(ICON_FILE))
        .replace("__OUTPUT_DIR__", str(OUTPUT_DIR))
        .replace("__OUTPUT_BASE__", output_base)
        .replace("__APP_GUID__", app_guid)
    )

    iss_path = os.path.join(OUTPUT_DIR, f"{SAFE_NAME}.iss")
    with open(iss_path, "w", encoding="utf-8") as f:
        f.write(iss_content)
    print(f"[installer] Wrote Inno script: {iss_path}")

    # Compile
    print(f"[installer] Compiling with: {iscc}")
    result = subprocess.run([iscc, iss_path], cwd=SCRIPT_DIR)
    if result.returncode != 0:
        sys.exit("[ERROR] Inno Setup compilation failed.")

    installer_path = os.path.join(OUTPUT_DIR, f"{output_base}.exe")
    print(f"[installer] Windows installer ready: {installer_path}")
    return installer_path


# ═══════════════════════════════════════════════════════════════════════════
# Linux — AppImage
# ═══════════════════════════════════════════════════════════════════════════

_DESKTOP_ENTRY = """\
[Desktop Entry]
Type=Application
Name={app_name}
Exec=main
Icon={icon_name}
Categories=Utility;Security;
Comment=Facial Recognition Security System v{app_version}
Terminal=false
"""

_APPRUN = """\
#!/bin/bash
# AppRun — entry point for the AppImage
SELF=$(readlink -f "$0")
HERE=$(dirname "$SELF")

# Ensure runtime dirs exist with correct permissions
mkdir -p "$HERE/faces_db/good" "$HERE/faces_db/bad"
mkdir -p "$HERE/metadata" "$HERE/targets" "$HERE/cache"
mkdir -p "$HERE/splash_assets" "$HERE/models"

export LD_LIBRARY_PATH="$HERE/usr/lib:$HERE:$LD_LIBRARY_PATH"
export PATH="$HERE/usr/bin:$HERE:$PATH"

exec "$HERE/main" "$@"
"""


def _find_appimagetool() -> str:
    """Locate appimagetool binary."""
    env = os.environ.get("APPIMAGETOOL", "")
    if env and os.path.isfile(env):
        return env
    found = shutil.which("appimagetool") or shutil.which("appimagetool-x86_64.AppImage")
    return found or ""


def _convert_ico_to_png(ico_path: str, png_path: str):
    """Best-effort conversion of .ico → .png using Pillow or magick."""
    try:
        from PIL import Image
        img = Image.open(ico_path)
        # Pick the largest icon size available
        sizes = img.info.get("sizes", set())
        if sizes:
            largest = max(sizes, key=lambda s: s[0] * s[1])
            img.size = largest
        img.save(png_path, format="PNG")
        return True
    except ImportError:
        pass

    magick = shutil.which("magick") or shutil.which("convert")
    if magick:
        subprocess.run([magick, ico_path, "-strip", png_path],
                       capture_output=True)
        if os.path.isfile(png_path):
            return True

    return False


def build_linux_installer():
    """Package the Nuitka dist into an AppImage."""
    print("\n[installer] Building Linux AppImage …")

    if not os.path.isdir(DIST_DIR):
        sys.exit(f"[ERROR] Nuitka dist not found at: {DIST_DIR}\n"
                 "        Run build.py first (on Linux or cross-compile).")

    appimagetool = _find_appimagetool()
    if not appimagetool:
        sys.exit(
            "[ERROR] appimagetool not found.\n"
            "        Download from: https://appimage.github.io/appimagetool/\n"
            "        Place it on PATH or set APPIMAGETOOL=/path/to/appimagetool"
        )

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Build an AppDir structure
    appdir = os.path.join(OUTPUT_DIR, f"{SAFE_NAME}.AppDir")
    if os.path.exists(appdir):
        shutil.rmtree(appdir)

    # Copy entire Nuitka dist into AppDir root
    print(f"[installer] Copying dist to AppDir …")
    shutil.copytree(DIST_DIR, appdir)

    # Ensure runtime directories exist inside the AppDir
    for subdir in [
        "faces_db/good", "faces_db/bad",
        "metadata", "targets", "cache",
        "splash_assets", "models",
    ]:
        os.makedirs(os.path.join(appdir, subdir), exist_ok=True)

    # Make the main binary executable
    main_bin = os.path.join(appdir, "main")
    if os.path.isfile(main_bin):
        os.chmod(main_bin, os.stat(main_bin).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    # Write AppRun
    apprun_path = os.path.join(appdir, "AppRun")
    with open(apprun_path, "w", newline="\n") as f:
        f.write(_APPRUN)
    os.chmod(apprun_path, 0o755)

    # Write .desktop file
    icon_name = SAFE_NAME.lower()
    desktop_path = os.path.join(appdir, f"{SAFE_NAME}.desktop")
    with open(desktop_path, "w", newline="\n") as f:
        f.write(_DESKTOP_ENTRY.format(
            app_name=APP_NAME,
            app_version=APP_VERSION,
            icon_name=icon_name,
        ))

    # Icon — AppImage expects a PNG at the AppDir root
    icon_png = os.path.join(appdir, f"{icon_name}.png")
    if os.path.isfile(ICON_FILE):
        if ICON_FILE.lower().endswith(".png"):
            shutil.copy2(ICON_FILE, icon_png)
        else:
            if not _convert_ico_to_png(ICON_FILE, icon_png):
                # Fallback: copy the .ico as-is (appimagetool may still accept it)
                shutil.copy2(ICON_FILE, icon_png)
                print("[installer] Warning: could not convert .ico to .png — "
                      "install Pillow or ImageMagick for best results.")
    else:
        print(f"[installer] Warning: icon not found at {ICON_FILE}")

    # Build the AppImage
    output_name = f"{SAFE_NAME}-{APP_VERSION}-x86_64.AppImage"
    output_path = os.path.join(OUTPUT_DIR, output_name)

    print(f"[installer] Running appimagetool …")
    env = os.environ.copy()
    env["ARCH"] = "x86_64"
    result = subprocess.run(
        [appimagetool, appdir, output_path],
        cwd=SCRIPT_DIR,
        env=env,
    )
    if result.returncode != 0:
        sys.exit("[ERROR] appimagetool failed.")

    # Cleanup AppDir (the .AppImage is self-contained)
    shutil.rmtree(appdir, ignore_errors=True)

    print(f"[installer] AppImage ready: {output_path}")
    return output_path


# ═══════════════════════════════════════════════════════════════════════════
# CLI
# ═══════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="Build platform installers from a Nuitka dist."
    )
    parser.add_argument(
        "--platform",
        choices=["windows", "linux", "all"],
        default=None,
        help="Target platform (default: auto-detect current OS)",
    )
    args = parser.parse_args()

    target = args.platform
    if target is None:
        target = "windows" if platform.system() == "Windows" else "linux"

    print(f"[installer] App: {APP_NAME}  v{APP_VERSION}")
    print(f"[installer] Dist: {DIST_DIR}")
    print(f"[installer] Output: {OUTPUT_DIR}")

    results = []

    if target in ("windows", "all"):
        results.append(build_windows_installer())

    if target in ("linux", "all"):
        results.append(build_linux_installer())

    print("\n" + "=" * 60)
    print("[installer] Done! Generated installers:")
    for r in results:
        print(f"  • {r}")
    print("=" * 60)


if __name__ == "__main__":
    main()
